import assert from 'node:assert/strict';
import {createWorkspace,snapshot,transact,GROSS_APY,FEE} from '../lib/product-ledger.mjs';
const now=1788790000000,year=365*86400000;
const workspace=createWorkspace(now),initial=snapshot(workspace,'individual',now),accountId=initial.account.id;
const op={mode:'individual',accountId,type:'deposit',amount:1000,requestId:'deposit-0001'};
transact(workspace,op,now);transact(workspace,op,now);assert.equal(snapshot(workspace,'individual',now).account.cash,9000);
assert.throws(()=>transact(workspace,{...op,amount:1001},now),/already used/);
assert.throws(()=>transact(workspace,{...op,amount:10000,requestId:'overdraw-1'},now),/exceeds/);
assert.throws(()=>transact(workspace,{...op,amount:-2,requestId:'negative-1'},now));
assert.throws(()=>transact(workspace,{...op,amount:.001,requestId:'precision-1'},now));
assert.throws(()=>transact(workspace,{...op,accountId:workspace.treasury.id,requestId:'scope-0001'},now),/not found/);
const annual=snapshot(workspace,'individual',now+year);assert.equal(annual.account.earned,Math.round(1000*GROSS_APY*(1-FEE)*100)/100);
transact(workspace,{...op,type:'withdraw',amount:500,requestId:'withdraw-0001'},now+year);
const half=snapshot(workspace,'individual',now+year);assert.equal(half.account.cash,9500);
assert.equal(Math.round((half.account.cash+half.account.earnBalance)*100),Math.round((10000+annual.account.earned)*100));
transact(workspace,{...op,type:'withdraw',amount:half.account.earnBalance,requestId:'withdraw-0002'},now+year);
const closed=snapshot(workspace,'individual',now+year);assert.equal(closed.account.earnBalance,0);assert.equal(closed.account.cash,10000+annual.account.earned);assert.equal(closed.account.events.length,3);
const treasuryBefore=snapshot(workspace,'institution',now);transact(workspace,{mode:'institution',accountId:workspace.customers[3].id,type:'deposit',amount:1000,requestId:'customer-0001'},now);const treasuryAfter=snapshot(workspace,'institution',now);assert.equal(treasuryAfter.account.cash,treasuryBefore.account.cash);assert.equal(treasuryAfter.metrics.clientPrincipal,treasuryBefore.metrics.clientPrincipal+1000);assert.equal(treasuryAfter.metrics.activeCustomers,4);
assert.equal(snapshot(createWorkspace(now),'individual',now).account.cash,10000);
console.log('Product ledger passed: isolated balances, deposit, idempotency, validation, account scope, net accrual, partial/full withdrawal, capital conservation, customer/treasury separation.');
